# Generated by Django 4.2.7 on 2024-10-27 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 21, 26, 10, 104538, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
