# Generated by Django 4.2.7 on 2024-10-27 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_phone_alter_event_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 21, 27, 44, 313356, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
