# Generated by Django 4.2.7 on 2024-10-23 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_date_created_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 1, 40, 19, 869877, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
