# Generated by Django 4.2.7 on 2024-10-23 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 8, 22, 22, 821178, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
